FROM openjdk:17-jdk-alpine
COPY target/webservices-order_management-0.0.1-SNAPSHOT.jar webservices-order_management-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/webservices-order_management-0.0.1-SNAPSHOT.jar"]